### ISSUE TITLE
feature request: скачивание альбома "фотографии со мной" и "фотографии с моей стены" 

### ISSUE THREAD

**Issue by argon338** [Gasoid/photoDumper#12]
Отлично работает приложение. Прям от души спасибо. 
Но столкнулся с тем, что у меня половина фото это "со мной" или "на стене", а приложение видит только основные альбомы пользователя. Возможно как то добавить?

**Comment by Gasoid** [comment]
Добрый день)
эти альбомы системные, не помню по какой причине я их убрал, надо протестить заново
можно через сваггер заставить скачать фотки, если есть навыки

**Comment by argon338** [comment]
> Добрый день)
> эти альбомы системные, не помню по какой причине я их убрал, надо протестить заново
> можно через сваггер заставить скачать фотки, если есть навыки

навыки есть, вспомнить надо :) пойду смотреть. Спасибо :)

**Comment by Gasoid** [comment]
тогда можно
https://github.com/Gasoid/photoDumper/blob/main/sources/vk/vk.go#L76
тут поменять на 
```go
resp, err := v.vkAPI.PhotosGetAlbums(api.Params{"need_covers": 1, "need_system": 1})
```
и альбомы появятся

**Comment by Gasoid** [comment]
но не уверен как будет работать

**Comment by argon338** [comment]
> но не уверен как будет работать

попробовал но у меня js скрипт рассыпался и страничка стала пустой. убираешь строчку - все ок (ну кроме того что нет альбомов указанных выше)

**Comment by Gasoid** [comment]
Надо запустить go generate
В ридми есть команды


пт, 6 янв. 2023 г., 15:51 argon338 ***@***.***>:

**Comment by argon338** [comment]
Генерация не помогает. 
Как только дополняем строчкой need Systems то на Фронте скрипт отваливается, но я не очень в JS поэтому не знаю где связь 
[Error] TypeError: null is not an object (evaluating 'e.items[r].thumb')
rv — Albums.js:13
wi — react-dom.production.min.js:166:139
wu — react-dom.production.min.js:289:389
yc — react-dom.production.min.js:279:392
hc — react-dom.production.min.js:279:323
mc — react-dom.production.min.js:279:180
oc — react-dom.production.min.js:270:91
rc — react-dom.production.min.js:267:432
rc
E — scheduler.production.min.js:13:205
M — scheduler.production.min.js:14:128

	ll (main.c8cf945f.js:2:91427)
	(anonymous function) (main.c8cf945f.js:2:91662)
	sa (main.c8cf945f.js:2:70800)
	gu (main.c8cf945f.js:2:121004)
	hu (main.c8cf945f.js:2:120437)
	mu (main.c8cf945f.js:2:119973)
	(anonymous function) (main.c8cf945f.js:2:132108)
	wc (main.c8cf945f.js:2:132570)
	rc (main.c8cf945f.js:2:125085)
	rc
	E (main.c8cf945f.js:2:164919)
	M (main.c8cf945f.js:2:165453)
[Error] TypeError: null is not an object (evaluating 'e.items[r].thumb')
	(anonymous function) (main.c8cf945f.js:2:132480)
	wc (main.c8cf945f.js:2:132570)
	rc (main.c8cf945f.js:2:125085)
	rc
	E (main.c8cf945f.js:2:164919)
	M (main.c8cf945f.js:2:165453)

**Comment by argon338** [comment]
https://github.com/Gasoid/photoDumper/blob/02e832c2ef5a39d51ecf59feab8b6430e0ba162d/sources/vk/vk.go#L82

системные альбомы начинаются со знаком минус, если забанить - начинает работать.

**Comment by Gasoid** [comment]
была какая то проблема связанная с этими альбомами, из за чего я убрал из релиза системные альбомы, как workaround можно скопировать наверное все фотки системных альбомов в другой

**Comment by Gasoid** [comment]
хотя нет скопировать не выйдет,
