### ISSUE TITLE
exif.Open Parsing file failed

### ISSUE THREAD

**Issue by kkalid** [Gasoid/photoDumper#14]
Привет, большое спс за такой труд! 
у меня такая проблема появилось "exif.Open Parsing file failed" после 987 фотографий
дальше пусто...

**Comment by Gasoid** [comment]
Добрый
попробуй поменять папку в которую скачиваешь
если будет тоже самое то вопрос
- какая версия?
- сколько всего файлов в альбоме?

**Comment by Gasoid** [comment]
reopen if it is necessary
