### ISSUE TITLE
Gratitude 🙏

### ISSUE THREAD

**Issue by Kif11** [Gasoid/photoDumper#19]
Thank you for developing and maintaining this tool!  I helped me to download all of my VK albums.

**Comment by Kif11** [comment]
I downloaded all albums. Individual albums didn't open for me in the UI.

**Comment by Gasoid** [comment]
![image](https://github.com/Gasoid/photoDumper/assets/833157/83b61625-6669-4e9f-a5b2-8f7052dcef21)
