### ISSUE TITLE
Is there a possibility to choose a destination folder?

### ISSUE THREAD

**Issue by alisa23a** [Gasoid/photoDumper#23]
How to set where to save downloaded pics? If there no such ability, then here is a feature request. Thank you.

**Comment by Gasoid** [comment]
hi
Next to blue button "Download all albums" you can set destination, by default it is home dir

**Comment by Gasoid** [comment]
![image](https://github.com/Gasoid/photoDumper/assets/833157/ed4caaa0-85c5-4dc0-91cb-79dc71899742)

**Comment by alisa23a** [comment]
@Gasoid thx
