### ISSUE TITLE
Download limited to 1000 photos 

### ISSUE THREAD

**Issue by SuchSkill** [Gasoid/photoDumper#29]
There seem to be a limit on 1000 photos to download 
![image](https://github.com/Gasoid/photoDumper/assets/20545718/6857f980-5f3a-4dd5-aa09-b180c3795fe7)
![image](https://github.com/Gasoid/photoDumper/assets/20545718/20ebd9f2-4181-4316-bc67-7c87c92a5bc0)

**Comment by Gasoid** [comment]
Can you test this build?
https://github.com/Gasoid/photoDumper/actions/runs/8438037871/artifacts/1359748370

**Comment by Gasoid** [comment]
I found bug regarding 1k actually, thank you!
Please download the latest version

https://github.com/Gasoid/photoDumper/releases/tag/1.1.3

**Comment by SuchSkill** [comment]
Works like a charm, thanks! Looks like I was right on time with that blazing fast fix
