### ISSUE TITLE
How to bypass the limit of 1000 photos per album?

### ISSUE THREAD

**Issue by onupirat** [Gasoid/photoDumper#9]

**Comment by Gasoid** [comment]
it is a "bug", because there was a hard limit. I am going to build a new version.

**Comment by Gasoid** [comment]
What OS do you use?

**Comment by Gasoid** [comment]
within 1 hour I am going to upload the 1.1.1 version where this issue has been fixed

**Comment by Gasoid** [comment]
@onupirat https://github.com/Gasoid/photoDumper/releases/tag/1.1.1
please test

**Comment by onupirat** [comment]
> @onupirat https://github.com/Gasoid/photoDumper/releases/tag/1.1.1 please test

still 1000 limit. Isn't this an API limit?

**Comment by onupirat** [comment]
But anyway, i found another way to download them so i'm no longer in need. Thank you for your effort.

**Comment by Gasoid** [comment]
thx 👍🏻

**Comment by azigriffin** [comment]
Still not fixed, can't download more than 1000 photo

**Comment by Gasoid** [comment]
it seems i've found the root cause, 
in v1.1.2 has been fixed the similar issue, you can try

**Comment by Gasoid** [comment]
I found the bug regarding 1k actually, thank you!
Please download the latest version

https://github.com/Gasoid/photoDumper/releases/tag/1.1.3
